### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by carstingaxion** [figuren-theater/ft-maintenance#1]
```[tasklist]
### Stories
- [ ] #2
- [ ] #3
- [ ] #4
- [ ] #5
- [ ] https://github.com/figuren-theater/ft-maintenance/issues/7
- [ ] #6
- [ ] https://github.com/figuren-theater/ft-maintenance/issues/14
```
```[tasklist]
### Plugins
- [ ] https://github.com/figuren-theater/ft-maintenance/issues/8
```

```[tasklist]
### misc. ToDos
- [ ] #28
- [ ] #44
```
